version: "3.5"
services:
  morning_sausage:
    container_name: morningsausage
    build: .
    init: true
    ports:
      - 80:8080
    restart: on-failure:3
    volumes:
      - ./frontend:/app/frontend
      - ./data:/app/data
      - ./log:/app/log